language: python
cache: pip
python:
  - '3.5'
  - '3.6'
before_script:
  - make codestyle
script:
  - make test
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
    python: '3.6'
